POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username": "Khang Pham",
  "password" : "khang@12345",
  "confirmPassword" : "khang@12345"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "Khang Pham",
  "password" : "khang@12345"
}

###
GET http://localhost:8080/api/v1/auth/authenticated
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJLaGFuZyBQaGFtIiwiaWF0IjoxNzc3ODczODc4LCJleHAiOjE3Nzc4NzM5NDh9.n-tULfAv6mzFlYYX6LfA2oU1_ABC_twD0yBkyFa7NQv3Q-6zieQw87gW2_4jCyerWGq5Ir1xW89uppINKxelEA
